title: 0x49D1's blog
description: Mostly programming stuff around .NET
#theme: minima
#remote_theme: mmistakes/minimal-mistakes
remote_theme: jekyll/minima@master
minima:
  skin: solarized-light
  show_excerpts: false
  show_image: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-toc
